#Configuration file used by Configuration as Code Plugin

#To see the available options go to the plugin documentation at YOUR_JENKINS_URL:8080/configuration-as-code/reference

#Set the Jenkins Admin User
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}  
  authorizationStrategy:
      globalMatrix:
        permissions:
          - "Overall/Administer:admin"
          - "Overall/Read:authenticated"  
  remotingSecurity:
      enabled: true                 

#Set new building authorization strategy with Plugin authorize-project 
#This will trigger pipelines with the user who requested the build
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy 

#Set the jenkins URL         
unclassified:
  location:
    url: http://localhost:8080/