FROM jenkins/jenkins:2.263.4-lts

VOLUME jenkins_home:/var/jenkins_home

#Disables the Setup Wizard
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/config-as-code.yml

EXPOSE 8080 50000

#Copies the file with the list of plugins to the container
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

#Runs the script to intall the plugins listed in the file
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

#Copies the configuration file to use with CASC Plugin
COPY config-as-code.yml /var/jenkins_home/config-as-code.yml
